Update to use Reflections 0.9.12
ExpediaGroup/jenkins-spock pull request #61
Opened 2020-02-28 17:06 UTC by rnc

Summary
==============================

This updates to Reflections 0.9.12 which changes the transitive tree of the project

Additional Details
==============================

Previously with 0.9.11 Reflections bought in Guava 20. This marks the FindBugs dependency as optional. This can cause problems in other projects which rely in Guava 11/Grape/GMavenPlus all of which combine to result in `Error grabbing grapes`. 
Given this project already states it requires >= Java 1.8, updating https://github.com/ronmamo/reflections 0.9.12 which has support for Java 8 and has _removed_ the Guava 20 dependency solves this entire strange dependency hell problem transparently :-) 

Checklist
==============================

Testing
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

* N/A I have manually verified that my code changes do the right thing.
* [x] I have run the tests and verified that my changes do not introduce any regressions.
* N/A I have written unit tests to verify that my code changes do the right thing and to protect my code against regressions

Documentation
-------------------------

(Remove this checklist and replace it with "N/A - no code changes" if this PR does not modify source code)

N/A - no code changes

2020-02-28 21:07 UTC, awittha requested changes
Looks good to me; tests pass on my end.

Would you mind adding an entry to the `UNRELEASED` section of `CHANGELOG.md` that encapsulates this change?

2020-02-28 23:34 UTC, rnc commented
@awittha Done ... did you want it squashed ?

2020-03-02 20:17 UTC, awittha commented
Yes, please squash.

2020-03-02 20:18 UTC, awittha approved these changes
Re-ran tests + ITs with Reflections 0.9.12; still passed.

2020-03-10 16:57 UTC, merged